export const GET_IMAGES: string = 'GET_IMAGES'
export const REMOVE_IMAGE: string = 'REMOVE_IMAGE'
export const LIKE_IMAGE: string = 'LIKE_IMAGE'
export const GET_LIKED_IMAGES: string = 'GET_LIKED_IMAGES'
export const GET_LIST: string = 'GET_LIST'
export const CHANGE_OPTION_LIKE: string = 'CHANGE_OPTION_LIKE'
export const CHANGE_OPTION_ALL: string = 'CHANGE_OPTION_ALL'